name: media_picker
description: Flutter plugin to get pictures and videos from the device.
version: 1.2.1
author: Duarte Silveira <dsilveira@gmx.net>
homepage: https://github.com/dsilveira/flutter_media_picker

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.mediaspicker
    pluginClass: MediasPickerPlugin

environment:
  sdk: ">=1.19.0 <3.0.0"
